# Generated by Django 5.2.15 on 2026-06-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    # Compatibility no-op. Some local databases recorded this migration before
    # skills.0002 existed; 0003 adds the final ManyToMany state after the
    # through model has been created.
    operations = []
