# Generated by Django 5.2.15 on 2026-08-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_application_priority_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="materials_pack",
            field=models.CharField(
                blank=True,
                choices=[("AI", "AI"), ("INFRA", "Infra")],
                help_text=(
                    "Golden resume pack copied into the local materials folder."
                ),
                max_length=16,
            ),
        ),
    ]
