# Generated by Django 5.2.15 on 2026-06-10 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        ("jobs", "0002_jobpost_employment_type_jobpost_external_id_and_more"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("OLLAMA_PIPELINE", "Ollama Pipeline"),
                            ("MANUAL", "Manual"),
                        ],
                        default="OLLAMA_PIPELINE",
                        max_length=40,
                    ),
                ),
                ("extraction_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_links",
                        to="applications.application",
                    ),
                ),
                (
                    "skill_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.skillset",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "skill_set__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "skill_set"),
                        name="unique_application_skill",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobPostSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("OLLAMA_PIPELINE", "Ollama Pipeline"),
                            ("MANUAL", "Manual"),
                        ],
                        default="OLLAMA_PIPELINE",
                        max_length=40,
                    ),
                ),
                ("extraction_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_links",
                        to="jobs.jobpost",
                    ),
                ),
                (
                    "skill_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.skillset",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "skill_set__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_post", "skill_set"), name="unique_jobpost_skill"
                    )
                ],
            },
        ),
    ]
