# Generated by Codex on 2026-06-10

from django.db import migrations


def ensure_skillset_timestamps(apps, schema_editor):
    table_name = "skills_skillset"
    existing_tables = schema_editor.connection.introspection.table_names()
    if table_name not in existing_tables:
        return

    columns = {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(),
            table_name,
        )
    }
    quoted_table = schema_editor.quote_name(table_name)

    for column_name in ("created_at", "updated_at"):
        quoted_column = schema_editor.quote_name(column_name)
        if column_name not in columns:
            schema_editor.execute(
                f"ALTER TABLE {quoted_table} ADD COLUMN {quoted_column} "
                f"{_datetime_column_type(schema_editor.connection)} NULL"
            )
        schema_editor.execute(
            f"UPDATE {quoted_table} SET {quoted_column} = CURRENT_TIMESTAMP "
            f"WHERE {quoted_column} IS NULL"
        )
        if schema_editor.connection.vendor == "postgresql":
            schema_editor.execute(
                f"ALTER TABLE {quoted_table} ALTER COLUMN {quoted_column} SET NOT NULL"
            )


def _datetime_column_type(connection):
    if connection.vendor == "postgresql":
        return "timestamp with time zone"
    if connection.vendor == "mysql":
        return "datetime(6)"
    return "datetime"


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_applicationskill_jobpostskill"),
    ]

    operations = [
        migrations.RunPython(ensure_skillset_timestamps, migrations.RunPython.noop),
    ]
