# Generated by Codex on 2026-06-10

import re

from django.db import migrations, models


def ensure_skillset_profile_fields(apps, schema_editor):
    table_name = "skills_skillset"
    existing_tables = schema_editor.connection.introspection.table_names()
    if table_name not in existing_tables:
        return

    cursor = schema_editor.connection.cursor()
    columns = {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            cursor,
            table_name,
        )
    }

    column_specs = {
        "normalized_name": _char_field("normalized_name", max_length=120),
        "aliases": _json_field("aliases"),
        "description": _text_field("description"),
        "is_active": _boolean_field("is_active"),
        "auto_created": _boolean_field("auto_created"),
    }
    for column_name, field in column_specs.items():
        if column_name not in columns:
            schema_editor.add_field(apps.get_model("skills", "SkillSet"), field)

    _backfill_skillset_rows(schema_editor.connection, table_name)
    _set_not_null(schema_editor, table_name, column_specs)
    _ensure_normalized_name_index(schema_editor, table_name)


def _char_field(name, max_length):
    field = models.CharField(max_length=max_length, null=True, blank=True)
    field.set_attributes_from_name(name)
    return field


def _json_field(name):
    field = models.JSONField(default=list, blank=True, null=True)
    field.set_attributes_from_name(name)
    return field


def _text_field(name):
    field = models.TextField(blank=True, null=True)
    field.set_attributes_from_name(name)
    return field


def _boolean_field(name):
    field = models.BooleanField(null=True)
    field.set_attributes_from_name(name)
    return field


def _backfill_skillset_rows(connection, table_name):
    quoted_table = connection.ops.quote_name(table_name)
    cursor = connection.cursor()
    cursor.execute(f"SELECT id, name FROM {quoted_table}")

    seen = set()
    for skillset_id, name in cursor.fetchall():
        normalized_name = _unique_normalized_name(name, skillset_id, seen)
        cursor.execute(
            (
                f"UPDATE {quoted_table} "
                "SET normalized_name = %s, "
                "aliases = COALESCE(aliases, %s), "
                "description = COALESCE(description, %s), "
                "is_active = COALESCE(is_active, %s), "
                "auto_created = COALESCE(auto_created, %s) "
                "WHERE id = %s"
            ),
            [
                normalized_name,
                _empty_json_value(connection),
                "",
                True,
                False,
                skillset_id,
            ],
        )


def _unique_normalized_name(name, skillset_id, seen):
    normalized_name = _normalize_name(name) or f"skill-{skillset_id}"
    if normalized_name not in seen:
        seen.add(normalized_name)
        return normalized_name

    deduped_name = f"{normalized_name}-{skillset_id}"
    seen.add(deduped_name)
    return deduped_name


def _normalize_name(name):
    normalized = re.sub(r"\s+", " ", str(name or "")).strip()
    normalized = normalized.strip(".,;:|/\\")
    return normalized.casefold()


def _empty_json_value(connection):
    if connection.vendor == "postgresql":
        return "[]"
    return []


def _set_not_null(schema_editor, table_name, column_specs):
    if schema_editor.connection.vendor != "postgresql":
        return

    quoted_table = schema_editor.quote_name(table_name)
    for column_name in column_specs:
        quoted_column = schema_editor.quote_name(column_name)
        schema_editor.execute(
            f"ALTER TABLE {quoted_table} ALTER COLUMN {quoted_column} SET NOT NULL"
        )


def _ensure_normalized_name_index(schema_editor, table_name):
    if schema_editor.connection.vendor != "postgresql":
        return

    quoted_table = schema_editor.quote_name(table_name)
    schema_editor.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS "
        "skills_skillset_normalized_name_uniq "
        f"ON {quoted_table} (normalized_name)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0003_ensure_skillset_timestamps"),
    ]

    operations = [
        migrations.RunPython(ensure_skillset_profile_fields, migrations.RunPython.noop),
    ]
