# Generated by Codex on 2026-06-10

import re

import django.db.models.deletion
from django.db import migrations, models


def backfill_skill_keywords(apps, schema_editor):
    SkillSet = apps.get_model("skills", "SkillSet")
    SkillKeyword = apps.get_model("skills", "SkillKeyword")

    for skill_set in SkillSet.objects.all().iterator():
        seen = set()
        keyword_rows = [(skill_set.name, "CANONICAL", True)]
        aliases = skill_set.aliases or []
        if isinstance(aliases, str):
            aliases = [aliases]
        keyword_rows.extend((alias, "ALIAS", False) for alias in aliases)

        for raw_text, source, is_primary in keyword_rows:
            clean_text = clean_keyword(raw_text)
            normalized_text = normalize_keyword(clean_text)
            if not normalized_text or normalized_text in seen:
                continue
            seen.add(normalized_text)
            SkillKeyword.objects.get_or_create(
                skill_set_id=skill_set.id,
                normalized_text=normalized_text,
                defaults={
                    "raw_text": clean_text,
                    "source": source,
                    "status": "ACTIVE",
                    "is_primary": is_primary,
                    "metadata": {"backfilled_from": "skillset"},
                },
            )


def clean_keyword(value):
    return re.sub(r"\s+", " ", str(value or "")).strip(" .,;:|/\\")


def normalize_keyword(value):
    normalized = clean_keyword(value)
    return normalized.casefold()


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0004_ensure_skillset_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_text", models.CharField(max_length=120)),
                ("normalized_text", models.CharField(db_index=True, max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CANONICAL", "Canonical"),
                            ("ALIAS", "Alias"),
                            ("MANUAL", "Manual"),
                            ("OLLAMA_EXTRACT", "Ollama Extract"),
                            ("OLLAMA_VERIFY", "Ollama Verify"),
                            ("MAPPED", "Mapped"),
                        ],
                        default="MANUAL",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CANDIDATE", "Candidate"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "skill_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="skills.skillset",
                    ),
                ),
            ],
            options={
                "ordering": ["skill_set__name", "-is_primary", "raw_text"],
                "indexes": [
                    models.Index(
                        fields=["normalized_text"],
                        name="skills_skil_normali_8528f6_idx",
                    ),
                    models.Index(
                        fields=["status", "normalized_text"],
                        name="skills_skil_status_399ba1_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("skill_set", "normalized_text"),
                        name="unique_skill_keyword_per_skillset",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_skill_keywords, migrations.RunPython.noop),
    ]
