# Generated by Codex on 2026-06-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0006_cleanup_legacy_skill_m2m_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.CharField(db_index=True, max_length=120, unique=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_aliases",
                        to="skills.skillset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "skill aliases",
                "ordering": ["alias"],
            },
        ),
    ]
