# Generated by Django 5.2.15 on 2026-06-20 08:27

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0007_skillalias"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="skillset",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
    ]
