# Generated by Django 5.2.15 on 2026-06-20 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0008_skillset_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillset",
            name="esco_uri",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("normalized_name", models.CharField(db_index=True, max_length=120)),
                (
                    "esco_uri",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="skills.skillcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "skill categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="skillset",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="skill_sets", to="skills.skillcategory"
            ),
        ),
        migrations.CreateModel(
            name="SkillRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("broader", "Broader"),
                            ("narrower", "Narrower"),
                            ("related", "Related"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="skills.skillset",
                    ),
                ),
                (
                    "target_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="skills.skillset",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "source_skill__name",
                    "relationship_type",
                    "target_skill__name",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="skillcategory",
            constraint=models.UniqueConstraint(
                fields=("parent", "normalized_name"),
                name="unique_skill_category_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="skillrelationship",
            constraint=models.UniqueConstraint(
                fields=("source_skill", "target_skill", "relationship_type"),
                name="unique_skill_relationship",
            ),
        ),
    ]
