# Generated by Django 5.2.14 on 2026-05-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("source_url", models.URLField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("URL", "URL"),
                            ("EMAIL", "Email"),
                            ("CSV", "CSV"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("remote_type", models.CharField(blank=True, max_length=50)),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_posts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
