# Generated by Django 5.2.15 on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_jobpost_skill_sets"),
        ("skills", "0002_applicationskill_jobpostskill"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="skill_sets",
            field=models.ManyToManyField(
                blank=True,
                related_name="job_posts",
                through="skills.JobPostSkill",
                to="skills.skillset",
            ),
        ),
    ]
