# Generated by Django 5.2.15 on 2026-08-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jobpost_internship_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("APPLIED", "Applied"),
                    ("CLOSED", "Closed"),
                    ("ARCHIVED", "Archived"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
