# Generated by Django 5.2.15 on 2026-08-25

from django.db import migrations, models


def populate_job_identity(apps, schema_editor):
    from apps.jobs.identity import JobIdentityService

    JobPost = apps.get_model("jobs", "JobPost")
    jobs = list(JobPost.objects.select_related("company").all())
    for job in jobs:
        identity = JobIdentityService.build(
            source_url=job.source_url,
            external_id=job.external_id,
            company_name=job.company.name,
        )
        job.canonical_source_url = identity.canonical_source_url
        job.normalized_external_id = identity.normalized_external_id
        job.source_key = identity.source_key
    JobPost.objects.bulk_update(
        jobs,
        [
            "canonical_source_url",
            "normalized_external_id",
            "source_key",
        ],
        batch_size=500,
    )


def clear_job_identity(apps, schema_editor):
    JobPost = apps.get_model("jobs", "JobPost")
    JobPost.objects.update(
        canonical_source_url="",
        normalized_external_id="",
        source_key="",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
        ("jobs", "0009_alter_jobpost_status"),
        ("skills", "0010_skill_intelligence_layers"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="canonical_source_url",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="normalized_external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="source_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=255,
            ),
        ),
        migrations.RunPython(populate_job_identity, clear_job_identity),
        migrations.AddConstraint(
            model_name="jobpost",
            constraint=models.UniqueConstraint(
                condition=~models.Q(canonical_source_url=""),
                fields=("canonical_source_url",),
                name="jobs_jobpost_unique_canonical_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobpost",
            constraint=models.UniqueConstraint(
                condition=(
                    ~models.Q(source_key="") & ~models.Q(normalized_external_id="")
                ),
                fields=("source_key", "normalized_external_id"),
                name="jobs_jobpost_unique_source_external_id",
            ),
        ),
    ]
