services:

  web:
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-config.settings.prod}

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "

    ports: []

    expose:
      - "80:8000"

    volumes:
      - static_volume:/app/src/staticfiles
      - media_volume:/app/src/media

  nginx:
    image: nginx:1.27

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static
      - media_volume:/media

    depends_on:
      - web

  db:
    ports: []

  redis:
    ports: []

  celery-worker:
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-config.settings.prod}

  celery-beat:
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-config.settings.prod}

volumes:
  static_volume:
  media_volume:
