# Generated by Django 5.2.15 on 2026-06-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_type', models.CharField(max_length=60)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('interviewer', models.CharField(blank=True, max_length=120)),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('feedback', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
