# Generated by ChatGPT on behalf of the project.
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("resource", models.CharField(choices=[("LINKEDIN", "LinkedIn"), ("HANDSHAKE", "Handshake"), ("GREENHOUSE", "Greenhouse"), ("LEVER", "Lever"), ("CAREER_SITE", "Career Site"), ("RSS", "RSS"), ("API", "API"), ("GENERIC_HTML", "Generic HTML")], default="GENERIC_HTML", max_length=20)),
                ("base_url", models.URLField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("crawl_interval_minutes", models.PositiveIntegerField(default=1440)),
                ("crawl_config", models.JSONField(blank=True, default=dict)),
                ("filter_config", models.JSONField(blank=True, default=dict)),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={"ordering": ["name"]},
        ),
    ]
