# Generated by Django 5.2.15 on 2026-06-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsource',
            options={},
        ),
        migrations.AlterField(
            model_name='jobsource',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobsource',
            name='resource',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('HANDSHAKE', 'Handshake'), ('GREENHOUSE', 'Greenhouse'), ('LEVER', 'Lever'), ('CAREER_SITE', 'Career Site'), ('RSS', 'RSS'), ('API', 'API'), ('GENERIC_HTML', 'Generic HTML')], max_length=20),
        ),
    ]
