# Generated by Django 5.2.15 on 2026-06-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_alter_jobsource_options_alter_jobsource_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsource',
            name='resource',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('HANDSHAKE', 'Handshake'), ('GREENHOUSE', 'Greenhouse'), ('LEVER', 'Lever'), ('CAREER_SITE', 'Career Site'), ('RSS', 'RSS'), ('API', 'API'), ('GENERIC_HTML', 'Generic HTML')], db_column='source_type', max_length=20),
        ),
    ]
