# Generated by Django 5.2.15 on 2026-06-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0003_alter_jobsource_resource"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_sources", models.PositiveIntegerField(default=0)),
                ("processed_sources", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("current_source", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
