# Generated by Django 5.2.15 on 2026-06-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0004_crawlrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlrun",
            name="errors",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlrun",
            name="jobs_closed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlrun",
            name="jobs_created",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlrun",
            name="jobs_updated",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
