# Generated by Django 5.2.15 on 2026-06-10 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("imports", "0005_crawlrun_errors_crawlrun_jobs_closed_and_more"),
        ("jobs", "0003_jobpost_skill_sets"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("service_name", models.CharField(blank=True, max_length=120)),
                ("step_name", models.CharField(db_index=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                            ("INFO", "Info"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_text", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_logs",
                        to="companies.company",
                    ),
                ),
                (
                    "crawl_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_logs",
                        to="imports.crawlrun",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_logs",
                        to="jobs.jobpost",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_logs",
                        to="imports.jobsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["step_name", "status"],
                        name="imports_pip_step_na_eacf3a_idx",
                    ),
                    models.Index(
                        fields=["severity", "created_at"],
                        name="imports_pip_severit_6279a2_idx",
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="imports_pip_source__5584c1_idx",
                    ),
                    models.Index(
                        fields=["crawl_run", "created_at"],
                        name="imports_pip_crawl_r_8e47dc_idx",
                    ),
                ],
            },
        ),
    ]
