# Generated by Django 5.2.15 on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0006_pipelinelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("ABORTED", "Aborted"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
