# Generated by Django 5.2.15 on 2026-06-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0007_alter_crawlrun_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsource",
            name="resource",
            field=models.CharField(
                choices=[
                    ("LINKEDIN", "LinkedIn"),
                    ("HANDSHAKE", "Handshake"),
                    ("GENERIC_HTML", "Generic HTML"),
                ],
                db_column="source_type",
                max_length=20,
            ),
        ),
    ]
