# Generated by Django 5.2.15 on 2026-06-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0008_alter_jobsource_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsource",
            name="resource",
            field=models.CharField(
                choices=[("LINKEDIN", "LinkedIn")],
                db_column="source_type",
                max_length=20,
            ),
        ),
    ]
