# Generated by Django 5.2.15 on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0009_alter_jobsource_resource"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobArchiveRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("cutoff_at", models.DateTimeField(db_index=True)),
                ("age_months", models.PositiveSmallIntegerField(default=3)),
                ("jobs_archived", models.PositiveIntegerField(default=0)),
                ("jobs_restored", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("RESTORED", "Restored"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("error_text", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
