# Generated by Django 5.2.15 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0010_jobarchiverun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsource",
            name="resource",
            field=models.CharField(
                choices=[
                    ("LINKEDIN", "LinkedIn"),
                    ("GREENHOUSE", "Greenhouse"),
                ],
                db_column="source_type",
                max_length=20,
            ),
        ),
    ]
