# Generated by Django 5.2.15 on 2026-06-21 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0009_esco_knowledge_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                ("occurrence_count", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("JOB_CRAWL", "Job Crawl"),
                            ("RESUME", "Resume"),
                            ("MANUAL", "Manual"),
                        ],
                        default="JOB_CRAWL",
                        max_length=20,
                    ),
                ),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "flagged_for_review",
                    models.BooleanField(db_index=True, default=False),
                ),
            ],
            options={
                "ordering": ["-occurrence_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="SkillDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_occurrences", models.PositiveIntegerField(default=0)),
                ("unique_jobs", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("rolling_30_day_count", models.PositiveIntegerField(default=0)),
                ("rolling_90_day_count", models.PositiveIntegerField(default=0)),
                ("demand_score", models.FloatField(db_index=True, default=0.0)),
                (
                    "skill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand",
                        to="skills.skillset",
                    ),
                ),
            ],
            options={
                "ordering": ["-demand_score", "skill__name"],
            },
        ),
        migrations.CreateModel(
            name="SkillTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trend_type",
                    models.CharField(
                        choices=[
                            ("rising", "Rising"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        db_index=True,
                        default="stable",
                        max_length=20,
                    ),
                ),
                ("growth_ratio", models.FloatField(default=1.0)),
                (
                    "skill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend",
                        to="skills.skillset",
                    ),
                ),
            ],
            options={
                "ordering": ["-growth_ratio", "skill__name"],
            },
        ),
    ]
