from dataclasses import dataclass, field


@dataclass(frozen=True)
class TaxonomyCategorySeed:
    name: str
    slug: str
    description: str = ""
    skill_names: list[str] = field(default_factory=list)
    skill_patterns: list[str] = field(default_factory=list)


BUSINESS_TAXONOMY: list[TaxonomyCategorySeed] = [
    TaxonomyCategorySeed(
        name="AI / ML",
        slug="ai-ml",
        description="Artificial intelligence and machine learning capabilities.",
        skill_names=[
            "LLM",
            "Large Language Models",
            "NLP",
            "Natural Language Processing",
            "Deep Learning",
            "Machine Learning",
            "Prompt Engineering",
            "Agentic AI",
            "Model Evaluation",
            "RAG",
            "LangChain",
            "LangGraph",
            "LlamaIndex",
            "Fine Tuning",
            "RLHF",
            "Vector Databases",
            "Embedding Models",
        ],
        skill_patterns=[
            "machine learning",
            "deep learning",
            "prompt",
            "llm",
            "language model",
            "rag",
            "langchain",
            "agentic",
            "embedding",
            "transformer",
            "pytorch",
            "tensorflow",
            "scikit",
        ],
    ),
    TaxonomyCategorySeed(
        name="Data Engineering",
        slug="data-engineering",
        description="Data pipelines, warehousing, and platform engineering.",
        skill_names=[
            "Big Data",
            "ETL",
            "ELT",
            "Data Modeling",
            "Data Warehousing",
            "Streaming Analytics",
            "Apache Spark",
            "Apache Kafka",
            "Apache Airflow",
            "dbt",
            "Snowflake",
            "Databricks",
            "Delta Lake",
            "Apache Iceberg",
            "Apache Hudi",
            "Apache Hadoop",
        ],
        skill_patterns=[
            "data engineer",
            "data pipeline",
            "data warehouse",
            "data modeling",
            "spark",
            "kafka",
            "airflow",
            "etl",
            "elt",
            "dbt",
            "snowflake",
            "databricks",
            "hadoop",
            "streaming",
        ],
    ),
    TaxonomyCategorySeed(
        name="Backend Engineering",
        slug="backend-engineering",
        description="Server-side application and API development.",
        skill_names=[
            "Django",
            "Django REST Framework",
            "FastAPI",
            "Flask",
            "Node.js",
            "Spring Boot",
            "GraphQL",
            "REST API",
            "Microservices",
            "PostgreSQL",
            "Redis",
        ],
        skill_patterns=[
            "backend",
            "api",
            "django",
            "fastapi",
            "flask",
            "spring",
            "microservice",
            "rest",
            "graphql",
        ],
    ),
    TaxonomyCategorySeed(
        name="Cloud Engineering",
        slug="cloud-engineering",
        description="Cloud infrastructure design and operations.",
        skill_names=[
            "AWS",
            "Amazon Web Services",
            "Azure",
            "Google Cloud Platform",
            "GCP",
            "Terraform",
            "OpenTofu",
            "Pulumi",
            "CloudFormation",
            "Amazon EKS",
            "Amazon ECS",
            "Azure AKS",
            "Google GKE",
        ],
        skill_patterns=[
            "cloud",
            "aws",
            "azure",
            "gcp",
            "terraform",
            "kubernetes",
            "eks",
            "ecs",
            "lambda",
            "cloudformation",
        ],
    ),
    TaxonomyCategorySeed(
        name="DevOps",
        slug="devops",
        description="Delivery automation, observability, and platform reliability.",
        skill_names=[
            "Docker",
            "Kubernetes",
            "CI/CD",
            "GitHub Actions",
            "Jenkins",
            "Argo CD",
            "Helm",
            "Prometheus",
            "Grafana",
            "Datadog",
        ],
        skill_patterns=[
            "devops",
            "docker",
            "kubernetes",
            "ci/cd",
            "jenkins",
            "helm",
            "prometheus",
            "grafana",
            "observability",
            "sre",
        ],
    ),
    TaxonomyCategorySeed(
        name="Database",
        slug="database",
        description="Relational and non-relational data stores.",
        skill_names=[
            "PostgreSQL",
            "MySQL",
            "MongoDB",
            "Redis",
            "Elasticsearch",
            "Cassandra",
            "DynamoDB",
            "SQL",
        ],
        skill_patterns=[
            "database",
            "sql",
            "postgres",
            "mysql",
            "mongodb",
            "redis",
            "elasticsearch",
            "cassandra",
        ],
    ),
    TaxonomyCategorySeed(
        name="Frontend Engineering",
        slug="frontend-engineering",
        description="User interface and client-side engineering.",
        skill_names=[
            "JavaScript",
            "TypeScript",
            "React",
            "Vue.js",
            "Angular",
            "Next.js",
            "HTML",
            "CSS",
            "Tailwind CSS",
        ],
        skill_patterns=[
            "frontend",
            "javascript",
            "typescript",
            "react",
            "vue",
            "angular",
            "next.js",
            "css",
            "html",
        ],
    ),
    TaxonomyCategorySeed(
        name="Cybersecurity",
        slug="cybersecurity",
        description="Security engineering and defensive operations.",
        skill_names=[
            "Cybersecurity",
            "Information Security",
            "Application Security",
            "Network Security",
            "Penetration Testing",
            "SIEM",
            "Zero Trust",
        ],
        skill_patterns=[
            "security",
            "cyber",
            "soc",
            "siem",
            "penetration",
            "vulnerability",
            "zero trust",
        ],
    ),
    TaxonomyCategorySeed(
        name="Software Engineering",
        slug="software-engineering",
        description="General software development practices and languages.",
        skill_names=[
            "Python",
            "Java",
            "Go",
            "C++",
            "Software Design",
            "Object-Oriented Programming",
            "Test-Driven Development",
            "Agile",
        ],
        skill_patterns=[
            "software engineer",
            "programming",
            "python",
            "java",
            "golang",
            "c++",
            "software design",
            "tdd",
            "agile",
        ],
    ),
]
