from dataclasses import dataclass, field

from .business_taxonomy_seed import TaxonomyCategorySeed


@dataclass(frozen=True)
class MarketCategorySeed(TaxonomyCategorySeed):
    pass


MARKET_TAXONOMY: list[MarketCategorySeed] = [
    MarketCategorySeed(
        name="Generative AI",
        slug="generative-ai",
        description="LLM, RAG, and generative application stack.",
        skill_names=[
            "RAG",
            "LangChain",
            "LangGraph",
            "LlamaIndex",
            "Prompt Engineering",
            "LLM",
            "Large Language Models",
            "Natural Language Processing",
            "Vector Databases",
            "Embedding Models",
            "Fine Tuning",
            "RLHF",
            "OpenAI API",
            "Claude API",
            "Gemini API",
        ],
        skill_patterns=[
            "generative",
            "llm",
            "rag",
            "langchain",
            "prompt",
            "embedding",
            "retrieval",
        ],
    ),
    MarketCategorySeed(
        name="Agentic AI",
        slug="agentic-ai",
        description="Autonomous and multi-agent AI systems.",
        skill_names=[
            "Agentic AI",
            "AI Agents",
            "Multi-Agent Systems",
            "AutoGen",
            "CrewAI",
            "Semantic Kernel",
        ],
        skill_patterns=["agentic", "agent", "multi-agent", "autogen", "crewai"],
    ),
    MarketCategorySeed(
        name="Big Data Technologies",
        slug="big-data-technologies",
        description="Large-scale data processing platforms.",
        skill_names=[
            "Apache Hadoop",
            "Apache Spark",
            "Big Data",
            "Apache Kafka",
            "Apache Flink",
            "Apache Hive",
            "Presto",
            "Trino",
        ],
        skill_patterns=["hadoop", "spark", "big data", "kafka", "flink", "hive"],
    ),
    MarketCategorySeed(
        name="Cloud Native",
        slug="cloud-native",
        description="Cloud-native infrastructure and delivery.",
        skill_names=[
            "Kubernetes",
            "Docker",
            "Terraform",
            "Helm",
            "Amazon EKS",
            "Amazon ECS",
            "Azure AKS",
            "Google GKE",
            "AWS",
            "Azure",
            "Google Cloud Platform",
        ],
        skill_patterns=[
            "cloud native",
            "kubernetes",
            "docker",
            "terraform",
            "helm",
            "eks",
            "serverless",
        ],
    ),
    MarketCategorySeed(
        name="Platform Engineering",
        slug="platform-engineering",
        description="Internal developer platforms and platform tooling.",
        skill_names=[
            "Kubernetes",
            "Terraform",
            "Helm",
            "Argo CD",
            "Backstage",
            "GitHub Actions",
            "CI/CD",
            "Infrastructure as Code",
        ],
        skill_patterns=[
            "platform engineer",
            "internal developer platform",
            "backstage",
            "platform",
            "iac",
        ],
    ),
    MarketCategorySeed(
        name="MLOps",
        slug="mlops",
        description="Operational machine learning lifecycle.",
        skill_names=[
            "MLOps",
            "MLflow",
            "Kubeflow",
            "Model Evaluation",
            "Model Monitoring",
            "Feature Store",
            "Machine Learning",
        ],
        skill_patterns=["mlops", "mlflow", "kubeflow", "model monitor", "feature store"],
    ),
    MarketCategorySeed(
        name="Data Platforms",
        slug="data-platforms",
        description="Modern data platform and lakehouse stack.",
        skill_names=[
            "Databricks",
            "Snowflake",
            "Delta Lake",
            "Apache Iceberg",
            "Apache Hudi",
            "dbt",
            "Data Warehousing",
        ],
        skill_patterns=[
            "data platform",
            "lakehouse",
            "databricks",
            "snowflake",
            "delta lake",
            "iceberg",
        ],
    ),
    MarketCategorySeed(
        name="Modern Data Stack",
        slug="modern-data-stack",
        description="Analytics engineering and modern BI stack.",
        skill_names=[
            "dbt",
            "Snowflake",
            "Apache Airflow",
            "ETL",
            "ELT",
            "Data Modeling",
            "Looker",
            "Tableau",
            "Power BI",
        ],
        skill_patterns=[
            "modern data stack",
            "dbt",
            "airflow",
            "analytics engineer",
            "looker",
            "tableau",
        ],
    ),
    MarketCategorySeed(
        name="AI Infrastructure",
        slug="ai-infrastructure",
        description="Infrastructure for training and serving AI workloads.",
        skill_names=[
            "CUDA",
            "GPU Computing",
            "NVIDIA",
            "Vector Databases",
            "Embedding Models",
            "Kubernetes",
            "AWS",
            "Model Serving",
        ],
        skill_patterns=[
            "ai infrastructure",
            "gpu",
            "cuda",
            "model serving",
            "inference",
            "vector database",
        ],
    ),
    MarketCategorySeed(
        name="Developer Productivity",
        slug="developer-productivity",
        description="Tools that improve engineering velocity.",
        skill_names=[
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "GitHub Actions",
            "Jira",
            "Confluence",
            "VS Code",
        ],
        skill_patterns=[
            "developer productivity",
            "github",
            "gitlab",
            "ci/cd",
            "vscode",
            "dev tooling",
        ],
    ),
]
